### PR TITLE
Fix hashcode changing between different executions (#2478)

### LINKED ISSUE #2478: Unable to deserialize a PacketContainer
- [x] This issue is not solved in a development build

**Describe the bug**
It seems that when you try to deserialize a PacketContainer it fails to do so.

**To Reproduce**
Serialize a packetContainer,
Reload / Restart the server
Deserialize it (Exception)

**Expected behavior**
Able to deserialize it

**Version Info**
[ProtocolLib DUMP](https://pastebin.com/72LiP6JX)

**How to fix it**
It seems that when looking up the the clazz of a PacketType it fails to find it that's because the hashcode of the deserialized PacketType doesn't match with the hashCode of the packetType inside the registry.

This is expected behavior bc the [specs](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Object.html#hashCode%28%29) doesn't guarantee the same hashcode for different executions

### PR DESCRIPTION
**Pull request by Mr-EmPee**
Fixes the issue that was preventing the deserialization of PacketContainers

closes #2478

### CODE REVIEW

**Comment by Mr-EmPee** [comment]
Another fix would be making the hashcode variable transient.
I prefer the suggested approach cause if anyone is using the hashcode function he can expect the value to remain the same

**Comment by derklaro** [comment]
Well if you open a PR to fix a bug it woild be really nice if you could explain in depth why the issue occurred in the first place ;)

**Comment by dmulloy2** [comment]
i think the real issue here is that it's relying on the hashCode being stable, which is not a safe assumption

**Comment by Mr-EmPee** [comment]
> Well if you open a PR to fix a bug it woild be really nice if you could explain in depth why the issue occurred in the first place ;)

All the details are in the linked issue.

> i think the real issue here is that it's relying on the hashCode being stable, which is not a safe assumption

I mean we could just put a transient on the cached variable, that would solve the problem without assuming that they maintain the same hashcode

**Comment by derklaro** [comment]
The linked issue does not describe where the problem originates from. It only generically describes an issue with serialising/deserializing packet containers...

**Comment by Mr-EmPee** [comment]
> The linked issue does not describe where the problem originates from. It only generically describes an issue with serialising/deserializing packet containers...

> It seems that when looking up the the clazz of a PacketType it fails to find it that's because the hashcode of the deserialized PacketType doesn't match with the hashCode of the packetType inside the registry.
> 
> This is expected behavior bc the [specs](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Object.html#hashCode%28%29) doesn't guarantee the same hashcode for different executions

To add more context, you serialize a packetContainer and when trying to deserialize it protocol lib does what I've describeded above and it fails.

**Comment by lukalt** [comment]
I think using `hashCode()` is unreliable when working with the Minecraft protocol in general. Most NMS packets do not properly implement equals() and hashCode()

**Comment by dmulloy2** [comment]
> > The linked issue does not describe where the problem originates from. It only generically describes an issue with serialising/deserializing packet containers...
> 
> 
> 
> > It seems that when looking up the the clazz of a PacketType it fails to find it that's because the hashcode of the deserialized PacketType doesn't match with the hashCode of the packetType inside the registry.
> 
> > 
> 
> > This is expected behavior bc the [specs](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Object.html#hashCode%28%29) doesn't guarantee the same hashcode for different executions
> 
> 
> 
> To add more context, you serialize a packetContainer and when trying to deserialize it protocol lib does what I've describeded above and it fails.
> 
> 
> 
> 

right, so in my mind a proper fix addresses the fact that serialization relies on hashCode instead of something stable

**Comment by Mr-EmPee** [comment]
> right, so in my mind a proper fix addresses the fact that serialization relies on hashCode instead of something stable

okay, I'm gonna try to add the modifier transient to the hashcode cache variable, that should fix the problem without
relaying on a specific custom behavior

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
