### PR TITLE
Performance patch

### PR DESCRIPTION
**Pull request by Jpx3**
* Convert a getDefault() != null check to a designated method hasDefault()
* Added a thread-safe and weak cache to the latter

### CODE REVIEW

**Comment by dmulloy2** [comment]
nice! would be interested to see the performance numbers if you have them

**Comment by Jpx3** [comment]
grafik

**Comment by dmulloy2** [comment]
@Jpx3 thank you! is that before or after?

**Comment by derklaro** [comment]
How about using guava `new MapMaker().weakKeys().makeMap()`? This would create a concurrent map (removes the need to compute the value for each thread) with weak keys. Just note that this technically creates a ConcurrentWeakIdentityMap - not sure if this is really relevant in this case.

**Comment by dmulloy2** [comment]
yeah that's a good point. is there any advantage to keeping it thread-local? i'd imagine classes are instantiable or not regardless of thread

**Comment by Jpx3** [comment]
Having it thread-local eliminates any locking by the map. This makes it thread-safe by design while still retaining its speed. And since we are talking about some class references and a few booleans, having some extra copies per thread doesn't matter that much.

**Comment by derklaro** [comment]
We're basically moving this problem behind the "plugins (or the server itself) start using virtual threads and users complain about performance again" barrier 😄

**Comment by Janmm14** [comment]
> We're basically moving this problem behind the "plugins (or the server itself) start using virtual threads and users complain about performance again" barrier 😄

I would hope at that point java virtual threads have a solution to handle this.

**Pull request merged**
