### PR TITLE
Implementing EntityPose

### PR DESCRIPTION
**Pull request by lewysDavies**
Added a Wrapper for EntityPose, which is contained in the Entity Metadata packet since 1.13+
This wrapper currently allows access to all 1.15.2 poses for use within the WrappedDataWatcher

**Usage:**
```
WrappedDataWatcher dataWatcher = new WrappedDataWatcher();
WrappedDataWatcherObject poseWatcher = new WrappedDataWatcherObject(6, 
        Registry.get(WrappedEntityPose.getNmsClass()));

WrappedEntityPose wrappedPose = WrappedEntityPose.fromValue(EntityPose.CROUCHING);
dataWatcher.setObject(poseWatcher, wrappedPose.getHandle());

// Send Metaupdate
```

**Previews:**
_CROUCHING_
image
_SLEEPING_
image

**Relevant Open Issues:**
#871 
#864

### CODE REVIEW

**Comment by dmulloy2** [comment]
This is better suited as an [EnumWrapper](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/EnumWrappers.java), it doesn't need to stand on its own.

**Comment by abhiram555** [comment]
**great work! this is what i wanted**

**Comment by abhiram555** [comment]
> Added a Wrapper for EntityPose, which is contained in the Entity Metadata packet since 1.13+
> This wrapper currently allows access to all 1.15.2 poses for use within the WrappedDataWatcher
> 
> **Usage:**
> 
> ```
> WrappedDataWatcher dataWatcher = new WrappedDataWatcher();
> WrappedDataWatcherObject poseWatcher = new WrappedDataWatcherObject(6, 
>         Registry.get(WrappedEntityPose.getNmsClass()));
> 
> WrappedEntityPose wrappedPose = WrappedEntityPose.fromValue(EntityPose.CROUCHING);
> dataWatcher.setObject(poseWatcher, wrappedPose.getHandle());
> 
> // Send Metaupdate
> ```
> 
> **Previews:**
> _CROUCHING_
> image
> _SLEEPING_
> image
> 
> **Relevant Open Issues:**
> #871
> #864

if you provide imports it will be good

**Comment by abhiram555** [comment]
why is this happening?
image

**Comment by abhiram555** [comment]
i tried to make player Pose like sleeping but player is only changing pose for 1 sec

**Comment by lewysDavies** [comment]
> 
> 
> This is better suited as an [EnumWrapper](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/EnumWrappers.java), it doesn't need to stand on its own.

I agree, and originally tried to implement it as a EnumWrapper. However, couldn't get it to work?

**Comment by lewysDavies** [comment]
> 
> 
> i tried to make player Pose like sleeping but player is waking up

I don't know why your player is waking up, maybe send the sleep packet every so often? idk

**Comment by lewysDavies** [comment]
I have implemented a basic starting point. Will be testing and finalising soon : )

**Comment by dmulloy2** [comment]
reasoning for using the faux enum converter? looks like a standard enum in NMS

**Comment by lewysDavies** [comment]
I only used Faux as it was used in the VillagerDataWrapper, switched to standard.

Promise I will finish this PR soon!!

**Comment by lewysDavies** [comment]
I have tested and all is working!
**Usage:**
```
import com.comphenix.protocol.wrappers.EnumWrappers.EntityPose;

WrappedDataWatcher dataWatcher = new WrappedDataWatcher();
WrappedDataWatcherObject poseWatcher = new WrappedDataWatcherObject(6, 
			Registry.get(EnumWrappers.getEntityPoseClass()));

EntityPose entPose = EntityPose.SWIMMING;
dataWatcher.setObject(poseWatcher, entPose.toNms());

// Send Metaupdate
```
image
image
image

**Comment by Cutiemango** [comment]
I tried to send the packet in 1.16, the packet is certainly received by the player, however it still puts the player back to the original state (STANDING).
Is there a method to make the player stay at that state?
My code is given below, correct me if there are any mistakes. (in Kotlin)
`// metadata
var dw = WrappedDataWatcher.getEntityWatcher(p)
var obj = WrappedDataWatcher.WrappedDataWatcherObject(6, WrappedDataWatcher.Registry.get(EnumWrappers.getEntityPoseClass()))
dw.setObject(obj, EnumWrappers.EntityPose.SLEEPING.toNms())

// send packet
val packet: PacketContainer = ProtocolLibrary.getProtocolManager().createPacket(PacketType.Play.Server.ENTITY_METADATA)
packet.integers.write(0, p.entityId)
packet.watchableCollectionModifier.write(0, dw.watchableObjects)
ProtocolLibrary.getProtocolManager().sendServerPacket(p, packet)`

**Comment by dmulloy2** [comment]
@Cutiemango you'll probably have to modify every outgoing metadata packet so it doesn't get reset

**Comment by Cutiemango** [comment]
Okay, so I tried to listen the metadata packet. But I don't really know how to check if the packet is modifying player's pose enum.
I have the code of creating the packet, so I guess it's the same logic of checking it.
However I'm not sure if I have to use PacketContainer#getWatchableCollectionModifier(), or PacketContainer#getDataWatcherModifier() to check it.
Also I don't quite understand how StructureModifier work, if I only need to check something, just use read() right?

**Pull request merged**
