### PR TITLE
Fix serializing and deserializing of ItemStack on 1.21

### PR DESCRIPTION
**Pull request by JustRed23**
Rewrites `StreamSerializer` to use the new ItemStack codec

### CODE REVIEW

**Comment by JustRed23** [comment]
Oh, one sec, I am incorrectly getting the STREAM_CODEC

**Comment by JustRed23** [comment]
Ready.

**Comment by dmulloy2** [comment]
could you re enable the unit tests as well?

**Comment by JustRed23** [comment]
Lmk if I missed one

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
