### PR TITLE
Add MCP packet names for Bukkit-Forge hybrid server

### LINKED ISSUE #858: ProtocolLib reports incorrect PacketType under CatServer (Bukkit-Forge hybrid server)
**Describe the bug**
This is a follow-up issue of #825.

While ProtocolLib does load and receive & send packets under CatServer, the received packet sometimes gives incorrect PacketType. This behaviour breaks plugins using PacketType to determine which packet is received.

**To Reproduce**
The reproduce example is using plugin FastLogin. Any other plugin should have the similar results.

Note that probably only a portion, not all of the PacketTypes are incorrectly identified.

1. Login to a server with FastLogin installed.
2. Stack trace printed to the console.

**Expected behavior**
Correct PacketType value is expected. In this case, the Login.Client.LoginInStart packet is recognized as another type, causing FastLogin to access non-existent fields.

I have not analyzed which type ProtocolLib gives, but adding two temporary packet listener using /packet command to Login.Client.Start and Login.Client.EncryptionBegin gives no message when a player logs in.

**Screenshots**
Exception stack traces: https://pastebin.com/sYJGCyup

**Version Info**
https://pastebin.com/Jf6Sq9RY

**Additional context**
A workaround fix for FastLogin games647/FastLogin#360 fixed the issue under CatServer, confirming ProtocolLib does report wrong PacketType.

### PR DESCRIPTION
**Pull request by NewbieOrange**
Fix ProtocolLib returning dynamic PacketType on forge servers, which breaks plugin using PacketType enums.

This PR will fix #858.

### CODE REVIEW

**Comment by NewbieOrange** [comment]
It seems that we cannot get reliable name on forge servers (which is expected). Adding PacketType lookup using packet id as a fallback will fix the issue.

I think adding such a fallback will not hurt reliablity or performance. Any thoughts?

**Comment by dmulloy2** [comment]
it wouldn’t have that much of an impact on performance. my main consideration is that packet ids change just about every version, so the 1.15 packet ids aren’t the same as the forge/1.12 ids

**Comment by dmulloy2** [comment]
it might be worthwhile to generate a mapping of forge packet names

**Comment by NewbieOrange** [comment]
I am looking into it and trying to figure out what could be done.

**Comment by NewbieOrange** [comment]
Hi @dmulloy2,

I have added some forge packet names and helper functions. I have tested this with FastLogin and it works.

Any thoughts? If you think this is doable, I will finish adding the rest of packet names.

**Comment by NewbieOrange** [comment]
I have added all MCP & Forge packet names up to 1.12.

**Comment by NewbieOrange** [comment]
Note that these names only works for minecraft 1.12. MC 1.13 and 1.14 both have different packet names. Considering that CatServer / Magma is still at 1.12 so far, this should be sufficient.

**Comment by NewbieOrange** [comment]
I have tested this and it works flawlessly with CatServer. I suppose it should work for Magma too, but not tested.

**Comment by Luohuayu** [comment]
> 
> 
> I have tested this and it works flawlessly with CatServer. I suppose it should work for Magma too, but not tested.

https://github.com/Luohuayu/CatServer/issues/208#issuecomment-653034465

**Comment by Luohuayu** [comment]
@NewbieOrange It seems still some problems

**Comment by NewbieOrange** [comment]
The changes is not in the release version. Try the lastest snapshot (#461+). @Luohuayu

**Pull request merged**
