### PR TITLE
Fixed protocol injection with latest netty on minecraft 1.11 and below

### PR DESCRIPTION
**Pull request by LewUwU**
Fix 'Can't find NetworkManager' with a newest version of netty and lower version of Minecraft
Code from https://github.com/aadnk/ProtocolLib/pull/175/commits/2e213338ecba4383ec28ac9f48d54e3d624cf3d5

-Tested and works great

### CODE REVIEW

**Comment by MacacoLew** [comment]
#1042

**Comment by dmulloy2** [comment]
Looks like the travis build is failing

**Comment by dmulloy2** [comment]
@MacacoLew update?

**Comment by tomcraft** [comment]
great work, hope it gets merged soon

**Comment by tomcraft** [comment]
@MacacoLew the `package` line is missing on `NettyVersion` class 

`package com.comphenix.protocol.utility;`

**Comment by MacacoLew** [comment]
oops

**Comment by tomcraft** [comment]
LGTM

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
