### PR TITLE
Updated Dependencies

### PR DESCRIPTION
**Pull request by Snowiiii**

### CODE REVIEW

**Comment by dmulloy2** [comment]
@derklaro Do you know if adventure needs to be kept in sync with paper, or is latest typically what we'll want?

**Comment by derklaro** [comment]
I think it makes no difference unless we accidentally use newer api internally 🤔 (idk how maven handles the provided scope... I hope that the dependency is not exposed like the compileOnly configuration of gradle)

**Comment by Snowiiii** [comment]
should work

**Comment by Snowiiii** [comment]
so will your merge or should I change adventure?

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
