### PR TITLE
Adding EntityType modifier to PacketContainer

### PR DESCRIPTION
**Pull request by verbuchselt**
Added EntityType modifier to PacketContainer, since PacketPlayOutSpawnEntity does not support EntityType-ids anymore

### CODE REVIEW

**Comment by Tofuus** [comment]
Any updates on the status of this PR?

**Comment by verbuchselt** [comment]
Hey @dmulloy2, could you please review this pull request, or are you currently too busy?

**Comment by 501warhead** [comment]
We've been waiting on a change to address the issue here for several months now, can we get an idea as to when this pull request can be reviewed?

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/a76ceb94cca987db71059a94003f6d7b1709fdb0

(didn't accept this one due to the unrelated changes. should've said that earlier, my bad)

**Pull request closed without merging**
