### PR TITLE
Replace MCstats with bStats

### PR DESCRIPTION
**Pull request by sgdc3**
#388

### CODE REVIEW

**Comment by MiniDigger** [comment]
somebody will need to create the page and add the custom chart

**Comment by dmulloy2** [comment]
I agree that mcstats is no longer viable. I'm not too familiar with bStats, but it looks like Paper and EssentialsX use it, so that's a pretty solid endorsement. I like the website design as well.

**Comment by sgdc3** [comment]
> somebody will need to create the page and add the custom chart

Yes, @dmulloy2 you have to register and create the plugin page and the custom graph, then you are ready to merge the PR.

**Comment by MiniDigger** [comment]
its basically exactly like mcstats just more modern and hopefully will be better supported by the author...

**Comment by sgdc3** [comment]
@MiniDigger he is working on a cluster system, he wants to make it even more stable.

**Comment by sgdc3** [comment]
@dmulloy2 any news?

**Comment by dmulloy2** [comment]
@sgdc3 Been busy with work and college, I can get this done tomorrow though

**Pull request merged**
