### PR TITLE
Update to 1.18.1

### PR DESCRIPTION
**Pull request by derklaro**
No changes required except for registering the protocol version

### CODE REVIEW

**Comment by Xonn1com** [comment]
isn't 1.18 almost the same as the 1.18.1?

**Comment by molor** [comment]
At least it will remove the warning message from console..
9+ days to merge a simple PR..

**Comment by dmulloy2** [comment]
> At least it will remove the warning message from console..
> 9+ days to merge a simple PR..

some of us have finals

**Comment by dmulloy2** [comment]
thanks again @derklaro !

**Pull request merged**
