### PR TITLE
Make getRandomKey() properly random

### PR DESCRIPTION
**Pull request by RodneyMKay**
In some scenarios, the system time source might give two identical values for `System.nanoTime()` during class intialization. This can cause a `ClassCastException` when we're trying to read the channel attributes, since the keys are no longer unique. This PR changes the `getRandomKey()` Method, so that we generate a proper pseudo-random number.

### CODE REVIEW

**Review by derklaro — CHANGES_REQUESTED** [review]
In general I have nothing to say against the argumentation why the change is needed, just that Random isn't thread safe either xdd  - Shoud probably use ThreadLocalRandom here :)

**Comment by RodneyMKay** [comment]
I might be overlooking something then 👀
As far as I saw, the method is only used twice in the intialisation of the static fields of this exact class (which can only happen on one thread).

**Comment by derklaro** [comment]
It can be constructed from `InjectionChannelInboundHandler#channelActive` which can be called from multiple netty event loops at the same time :)

**Comment by RodneyMKay** [comment]
All of the fields this relates to are static though (and therefore only initialised once, afaik) 😅

**Comment by derklaro** [comment]
OH, I missed that completely... Sorry - would still use ThreadLocalRandom there to make the diff smaller and prevent the random field which is only used twice :)

**Comment by RodneyMKay** [comment]
Ah, okay, I'll change it immediately ^^

**Comment by RodneyMKay** [comment]
Fixed :)

**Review by derklaro — APPROVED** [review]

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
