### PR TITLE
Add BlockEntityType support.

### LINKED ISSUE #1470: API representation for packet fields of type BlockEntityType
For example, in MC 1.18.x, the TILE_ENTITY_DATA packet (ClientboundBlockEntityDataPacket) stores a field of type BlockEntityType. I am not sure how I can analyze this field via ProtocolLib, for example to conditionally only modify packets that affect a specific type of tile entity.

Possible solutions I can think of:
* Add a new converter to [BukkitConverters](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/BukkitConverters.java) that converts objects of type BlockEntityType to something NMS-unspecific, such as: The corresponding Bukkit BlockState class, ProtocolLib's MinecraftKey, Bukkit's NamespacedKey, the String key, ..
* Expose a wrapper for Minecraft's BlockEntityType registry in [WrappedRegistry](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/WrappedRegistry.java). This would then allow the lookup of the key for a given BlockEntityType instance.

### PR DESCRIPTION
**Pull request by portlek**
Looks like fixes #1470 .-.

```java
final var writeToSign = new PacketContainer(PacketType.Play.Server.TILE_ENTITY_DATA);
writeToSign.getBlockPositionModifier().write(0, position);
writeToSign.getBlockEntityTypeModifier().write(0, WrappedRegistrable.blockEntityType("sign"))
writeToSign.getNbtModifier().write(0, compound);
```
image

### CODE REVIEW

**Comment by portlek** [comment]
@dmulloy2 could you please review, thank you ^.^

**Comment by dmulloy2** [comment]
> @dmulloy2 could you please review, thank you ^.^

will take a closer look tomorrow. first thought is that the wrapper looks like it might be applicable to more things than just block entity types

**Comment by portlek** [comment]
i see what you mean, i'm gonna try to make it more abstract so we can use it whenever it needs to be.

**Comment by portlek** [comment]
how about this one @dmulloy2

**Comment by TechsCode** [comment]
@dmulloy2 could you please review it, we need this as it’s really urgent. We all would appreciate it! 

I hope you can help us

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
