### PR TITLE
Improve getEntityFromID

### PR DESCRIPTION
**Pull request by Machine-Maker**
First time contributing, so not 100% sure on how reflection stuff is handled, but the server keeps a map of entities by ID, so iterating over all the entities in a world isn't the best way to get an entity from its ID.

### CODE REVIEW

**Review by derklaro — COMMENTED** [review]
I think that using fuzzy (returns Entity, takes id) might be better than relying on the method name?

**Comment by Machine-Maker** [comment]
> I think that using fuzzy (returns Entity, takes id) might be better than relying on the method name?

yeah, problem is, there are two methods that do that on ServerLevel. one takes into account the dragon parts which are stored separately, the other doesn't.

**Comment by dmulloy2** [comment]
Which versions does this work on? Typically relying on the field name and not fuzzy reflection that list is pretty limited

**Comment by Machine-Maker** [comment]
> Which versions does this work on? Typically relying on the field name and not fuzzy reflection that list is pretty limited

yeah this is just using 1.18.2 mappings. How would you suggest I go about it? Fuzzy reflection will match two methods right?

**Pull request closed without merging**
