### PR TITLE
JSON Parsing for WrappedServerPing and fixed modifying favicon

### PR DESCRIPTION
**Pull request by lukalt**
- Added wrappers for Encoding/Decoding using the Mojang Serialization Library
- Implement JSON Encoding/Decoding of ServerPing for 1.19.4 (@molor)
- Fix redundant Base64 encoding and prefixing of server icons that are modified using ProtocolLib (#2354)

### CODE REVIEW

**Comment by dmulloy2** [comment]
yeah my plan is to hold off on json for the new server ping until/unless it's requested. not sure of the use case for it

**Comment by molor** [comment]
Our main/lobby server sometimes pings our other/mini-servers and returns their MOTD's instead of self MOTD, so I'm probably the first one who needs `WrappedServerPing#fromJson`...

**Comment by lukalt** [comment]
> Our main/lobby server sometimes pings our other/mini-servers and returns their MOTD's instead of self MOTD, so I'm probably the first one who needs `WrappedServerPing#fromJson`... Sadly that it's no longer possible ):

As a temporary workaround, I would suggest to try serializing the underlying handle using gson. Something like this.

Serialize:
```
WrappedServerPing ping = ...;
String json = new Gson().toJson(ping.getHandle());
```

Deserialization:
```
WrappedServerPing = WrappedServerPing.fromHandle(new Gson().fromJson(json, MinecraftReflection.getServerPingClass()));
```

Please note that this only works if both the serializing and the deserializing server run the same Minecraft Version

**Comment by lukalt** [comment]
@dmulloy2 I now implemented proper JSON parsing and updated this pull request

**Review by dmulloy2 — APPROVED** [review]

**Comment by dmulloy2** [comment]
thank you!

**Pull request merged**
