### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by CDAGaming**

### CODE REVIEW

**Comment by dmulloy2** [comment]
What's the purpose of this?

**Comment by CDAGaming** [comment]
IT's just an update on a few dependencies, if it's not needed you can close this.

**Comment by CDAGaming** [comment]
@dmulloy2 One month Later 👍

**Comment by dmulloy2** [comment]
Right, so this isn't really a meaningful change; updating dependencies doesn't tend to do much unless there are breaking changes in the runtime environment that need to be addressed

**Pull request closed without merging**
