### PR TITLE
Update to minecraft 1.18

### PR DESCRIPTION
**Pull request by derklaro**
This tracks the update changes to minecraft 1.18.

* 11-22-2021: Introduces support for the last spigot release 1.18-pre5 as announced [here](https://www.spigotmc.org/threads/9-years-of-spigotmc-spigot-bungeecord-1-18-pre5.534760/)
* 11-24-2021: Support for 1.18-pre8 - some packet classes are now records
* 11-30-2021: Caves and Cliffs Part II was released :tada:

### CODE REVIEW

**Comment by derklaro** [comment]
Will do this later today, thank you!

**Comment by derklaro** [comment]
Noticed another issue with the non-relocated dependencies. Everything else looked fine when i was testing on monday without any changes.

**Comment by derklaro** [comment]
Should be good to go know. Changes were tested against latest 1.18-pre5 builds, 1.8.8 and 1.17.1

**Comment by derklaro** [comment]
The changes for 1.18-pre8 are required as mojang decided to make some package classes records which have restricted field access. The workaround i implemented now is that the ObjectWriter is actually either cloning the fields or if the class is a record it will find the all-args constructor (which is required for records) and creates a new instance with all field values of the old instance to clone.

**Comment by derklaro** [comment]
To summaraize the latest commit: Hacks to prevent Java from preventing us to write to final fields in records. This method should work for the next few java versions going onward...

**Comment by quiquelhappy** [comment]
Thanks a lot for working on thus

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
