### PR TITLE
Add AdventureComponentConverter#fromComponentObject

### PR DESCRIPTION
**Pull request by iiAhmedYT**
Helps when relocating Adventure on your plugin and still listening to packets containing adventure components

### CODE REVIEW

**Comment by Ingrim4** [comment]
What are the use cases if you can already do: `fromComponent((Component) component);`?

**Comment by iiAhmedYT** [comment]
It's used incase you can't do that, i think that should be clear o.O

PtotocolLib is a hacky reflective workaround for packets so using reflections with it and other hacky code is totally expected

**Comment by Ingrim4** [comment]
> It's used incase you can't do that, i think that should be clear o.O
> 
> ProtocolLib is a hacky reflective workaround for packets so using reflections with it and other hacky code is totally expected (especially with what paper does to packets nowadays)

Firstly, why is this necessary when the method you added doesn't add any new functionality? Secondly, I don't see a clear use case for this addition. All it does is cast an object to a component, which you can also do in your own code. Can you clarify the specific scenarios where this would be beneficial?

**Comment by iiAhmedYT** [comment]
Im not home to explain it with high detail but here is simple one that requires you to read the description of the pr again


If i cast my component object to my.relocated.adventure.Component

that won't work with net.kyori.adventure.Component


especially that i got that component from ProtocolLib from the system chat packet so it uses the default location not the relocated one

because thats what relocation does 😄

**Review by dmulloy2 — APPROVED** [review]

**Pull request merged**
