### PR TITLE
fixed #1813

### LINKED ISSUE #1813: StreamSerializer compatible issues
- [x] This issue is not solved in a development build

**Describe the bug**
ItemStack serialized by 4.x's cannot deserialize by 5.0.0

**To Reproduce**
1. Serialize ItemStack by StreamSerializer.serializeItemStack on ProtocolLib-4.8.0
2. Deserialize on ProtocolLib-5.0.0 from CI
3. You got an exception

**Expected behavior**
:-)

**Screenshots**
None

**Version Info**
4.8.0

**Additional context**
None

### PR DESCRIPTION
**Pull request by caoli5288**
Fix compatible with old release

### CODE REVIEW

**Comment by derklaro** [comment]
You're not really fixing anything - you're just reverting a change to use an unsupported spigot dependency which might change at any time (even tough md5 will probably keep the dep for the next 20 years anyway). There must be a way to resolve the issue using java.util.Base64... Please either change you pull request like that or provide a test string in the original issue (input which isn't working + expected output) so that I can take a look at that :)

**Comment by caoli5288** [comment]
> You're not really fixing anything - you're just reverting a change to use an unsupported spigot dependency which might change at any time (even tough md5 will probably keep the dep for the next 20 years anyway). There must be a way to resolve the issue using java.util.Base64... Please either change you pull request like that or provide a test string in the original issue (input which isn't working + expected output) so that I can take a look at that :)

Old one decoded string contains \n

**Comment by derklaro** [comment]
Just give me an example string...

**Comment by caoli5288** [comment]
> Just give me an example string...

```java
import org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder

def b = Base64Coder.decodeLines("AW8BAAAKAAAKAAdkaXNwbGF5CQAETG9yZQgAAAACABzCp3LCp2blm57lpI3Cp3I0wqdy54K56aWx\n6aOfACHCp3LCpzfmnInmpoLnjofojrflvpfppaXppb9kZWJ1ZmYIAAROYW1lABjCp3LCp2bohZDo\ntKXnmoTogonnvZDlpLQACAACaWQABnJvdHRlbgYAA3JpZD/jCQastcr7CAAEdHlwZQAEdGlueQAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==")

def a = Base64.decoder.decode("AW8BAAAKAAAKAAdkaXNwbGF5CQAETG9yZQgAAAACABzCp3LCp2blm57lpI3Cp3I0wqdy54K56aWx6aOfACHCp3LCpzfmnInmpoLnjofojrflvpfppaXppb9kZWJ1ZmYIAAROYW1lABjCp3LCp2bohZDotKXnmoTogonnvZDlpLQACAACaWQABnJvdHRlbgYAA3JpZD/jCQastcr7CAAEdHlwZQAEdGlueQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==")

Arrays.equals(a, b) // true
```

**Comment by caoli5288** [comment]
If you don't want to revert, then deleting \n at each call will solve the problem, although I don't think it's a good idea.

**Comment by derklaro** [comment]
You don't need to - just replace `Base64.getDecoder` with `Base64.getMimeDecoder` (and encoder) and the issue should be solved

**Comment by derklaro** [comment]
And it would be nice to get a test for that - if you can spare out a few minutes :)

**Comment by caoli5288** [comment]
> You don't need to - just replace `Base64.getDecoder` with `Base64.getMimeDecoder` (and encoder) and the issue should be solved

That's true.

**Pull request closed without merging**
