### PR TITLE
add support for sync & async receiving listeners

### PR DESCRIPTION
**Pull request by derklaro**
Add support to register receive listeners to call them either async or on the main thread. There was a lot of confusion in issues when receive listeners for (seemingly) some reason were called async without spcifying the async option - directly on the netty event loop. This is an issue for 2 reasons:
 1. some plugins want to access bukkit api in receive listeners, like getting the interacted block.
 2. doing stuff on the netty event loop blocks that event loop from doing other stuff, like polling more inbound messages which can lead to delays (especially considering that spigot limits event loop threads to 4 by default). Therefore I moved incoming events to an async bukkit scheduler thread if the receive process is called in the event loop (which it always should be). A small reference what can happen when doing work on the event loop vs. not doing it can be seen here: https://twitter.com/fbrasisil/status/1163974576511995904
 3. if a plugin decided to go the "cancel packet -> sync work -> use `Injector#receiveClientPacket`" way it prevented other channel listeners from being able to do work with the plugin. Normally there shouldn't be any vanilla decoders after our decoder, but for example other plugins that hooked into the pipeline might have issue seeing intercepted packets.

### CODE REVIEW

**Review by jiajiaxd — APPROVED** [review]

**Review by dmulloy2 — APPROVED** [review]

**Comment by Kapitowa** [comment]
This changes fully broke damage to mobs with diamond sword and etc.

**Comment by derklaro** [comment]
@Kapitowa Please open a new issue then and attach the dump & any exceptions you see. I just re-tested this and it seems to work as expected for me 🤔

**Comment by Shevchik** [comment]
Throwing packets in async tasks means that intercepted packets may be processed out of order (because async tasks spawn new threads for each task), while previously it wasn't so. A separate thread bound to a player must be used instead.

**Comment by Bobcat00** [comment]
I'm listening for Server.KEEP_ALIVE and Client.KEEP_ALIVE and the timing is wrong in 1.19.2 with build 597. How do I specify async (immediate) processing for my listeners? The code looks like this:
```
protocolManager.addPacketListener(new PacketAdapter(plugin,
                                                    ListenerPriority.NORMAL,
                                                    PacketType.Play.Client.KEEP_ALIVE) {
            @Override
            public void onPacketReceiving(PacketEvent event) {
```

**Comment by derklaro** [comment]
@Shevchik you're right - we removed that behaviour a few hours after merging this pull request
@Bobcat00 you (for now) need to specify the "async" option, imo the best way to do that is using PacketAdapterParams like: 
```java
new PacketAdapter(PacketAdapter.params(plugin, PacketType.Play.Client.KEEP_ALIVE).optionAsync())
```

**Comment by Bobcat00** [comment]
> you (for now) need to specify the "async" option,

Thank works - Thanks! But by "for now", do you think this will change in the near future?

**Comment by derklaro** [comment]
Either today or tomorrow 🤷

**Pull request merged**
