### PR TITLE
Fix EntityUseAction & Hand read for minecraft 1.17

### LINKED ISSUE #1227: 1.17 USE_ENTITY entity use action IndexOutOfBoundsException
**Describe the bug**
Seems USE_ENTITY packet is changed.
`This server is running CraftBukkit version 3143-Spigot-66f9d3c-f66c437 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`
` ProtocolLib version 4.7.0-SNAPSHOT-b509`

Code at line 69 
```java
packet.getEntityUseActions().getValues().get(0)
```

Log:
```
[12:43:47] [Netty Server IO #1/ERROR]: [ItemsAdder] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemsAdder
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at dev.lone.itemsadder.Core.ItemsDynamicity.Behaviours.BukkitEventsHandlers.PlaceableEntityEventsHandler$1.onPacketReceiving(PlaceableEntityEventsHandler.java:69) ~[ItemsAdder.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.0-SNAPSHOT-b509]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:3143-Spigot-66f9d3c-f66c437]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:43:47] [Netty Server IO #1/ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayInUseEntity@47fbd730[
    a=838
    b=net.minecraft.network.protocol.game.PacketPlayInUseEntity$1@301955ba
    c=false
  ]

>
```

### PR DESCRIPTION
**Pull request by derklaro**
This pull request fixes the read of the entity interact actions for the USE_ENTITY packet as it got wrapped into a special interface. Maybe the introduced Method/Field accessor in MinecraftReflection should be a lazy initialized field to prevent many reflection lookups (please give feedback).

~~This pull requests introduces a new structure modifier in the Packetcontainer class for allow access to the Hand field in the UseEntity packet for 1.17+ as it got wrapped into an interface implementation (for interact & interact_at). Other packets still have the hand enum so adding the method is required for the correct read access to the method.~~

This change was tested on Spigot `3149-Spigot-101ebb6-9122f5a (MC: 1.17)` and the experimental paper 1.17 dev build.

Fixes #1227

### CODE REVIEW

**Comment by derklaro** [comment]
I'm currently thinking about a fix for the hand to be readable in other packets where it is unwrapped :/

**Comment by dmulloy2** [comment]
Looks great! Could you add a unit test or two for this?

**Comment by derklaro** [comment]
During the write of the tests i saw that writing to the packet using the current modifiers is not easy at all because for example the hand is wrapped in a class in the packet class. Technically it is possible to write to these fields but it's not easy at all. On the other hand, changing the action completely was only possible by writing own reflection code. Sorry that i didn't see that earlier.

To fix this problem i added a wrapper for the class in the packet. It allows read/write access to the fields in the class and an easy way to modify the action performed by the user completely. Read/write access to the field is available by using `PacketContainer#getEnumEntityUseActions`.

Tests for the change are now present and the new change was tested on spigot & paper again.

**Review by dmulloy2 — APPROVED** [review]

**Comment by dmulloy2** [comment]
Looks great, thank you so much!

**Pull request merged**
