### PR TITLE
Some General optimizations

### PR DESCRIPTION
**Pull request by Snowiiii**

### CODE REVIEW

**Comment by derklaro** [comment]
I personally feel like this pr does introduce new problems, as well as brining a lot of merge conflicts to other open prs. I have nothing against reformatting the code, but this makes it worse at sme points (and dependency updates definitely do not belong here as well)

**Comment by Snowiiii** [comment]
I see your point, I just wanted to add some clarity and cleanliness to the code

**Comment by derklaro** [comment]
I think thats fine in general, but at the moment doing that would break some other stuff so maybe moving that back is better than having to deal with 100 merge conflicts 😂

**Comment by Snowiiii** [comment]
Could you accept the pr if I undo some commits just tell me which ones ?

**Comment by derklaro** [comment]
I'm not a Collaborator of this repository, I'm just brining in my opinion 🤷

**Comment by dmulloy2** [comment]
So this is basically just a code format?

**Comment by Snowiiii** [comment]
basically yes

**Pull request closed without merging**
