### PR TITLE
Some folia fixes

### PR DESCRIPTION
**Pull request by Anon8281**
Fix some bukkit scheduler moments. Also covering #2449

### CODE REVIEW

**Comment by ewof** [comment]
```
[16:04:13 ERROR]: [ProtocolLib] Error initializing plugin 'ProtocolLib-5.1.0-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/scaffold/subclass/ConstructorStrategy
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:129) ~[ProtocolLib-5.1.0-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[folia-1.20.1.jar:git-Folia
-"34039e3"]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[folia-1.20.1.jar:git-Folia
-"34039e3"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.scaffold.subclass.ConstructorStrategy
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
```

```
[16:04:14 WARN]: [LuckPerms] Thread luckperms-worker-1 threw an uncaught exception
java.lang.RuntimeException: java.lang.IllegalStateException: zip file closed
        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.lambda$static$0(GeneratedEventClass.java:70) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.lucko.luckperms.common.cache.LoadingMap.get(LoadingMap.java:67) ~[?:?]
        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.generate(GeneratedEventClass.java:81) ~[?:?]
        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.preGenerate(GeneratedEventClass.java:89) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:130) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[folia-1.20.1.jar:git-Folia-"34
039e3"]
        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:173) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:574) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.lucko.luckperms.lib.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:207) ~[?:?]
        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.<init>(GeneratedEventClass.java:112) ~[?:?]
        at me.lucko.luckperms.common.event.gen.GeneratedEventClass.lambda$static$0(GeneratedEventClass.java:68) ~[?:?]
        ... 10 more
```


btw ty for ur work im using ur brewery fork and some other stuff too

**Comment by lukalt** [comment]
@ewof I think you are using the wrong Jar. You need to be using `build/libs/ProtocolLib.jar`, not  `build/libs/ProtocolLib-5.1.0-SNAPSHOT.jar`. The latter one does not shadow any required dependencies.

**Comment by ewof** [comment]
i dont get one generated when i do `./gradlew build` only snapshot ones

**Comment by ewof** [comment]
nvm

**Comment by Anon8281** [comment]
Thank you for report. Looks like you should use **ProtocolLib.jar** coming from `shadowJar` task.
> java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/scaffold/subclass/ConstructorStrategy

Btw, could you please star my github project(https://github.com/Anon8281/UniversalScheduler) to get this lib && Folia more popular?

**Review by dmulloy2 — APPROVED** [review]

**Review by dmulloy2 — DISMISSED** [review]

**Pull request merged**
