### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by derklaro**
As announced by Mojang [here](https://www.minecraft.net/de-de/article/the-wild-update-coming) the (w/m)ild update is on the way. Currently this pr only prepares for the upcoming changes (as spigot has not yet released a pre-release) based on the official 1.19-pre3 mappings (see the full packet list of 1.19 [here](https://github.com/derklaro/mc-protocol)).

Will see if there are any upcoming changes in the next days and will make any changes accordingly :shipit:

### CODE REVIEW

**Comment by derklaro** [comment]
image

**Comment by derklaro** [comment]
If someone wants to test this and give feedback, you can download the running version from [here](https://cdn.discordapp.com/attachments/946646266811674714/983826994934468658/ProtocolLib.jar).

⚠️  **Please note that plugins might need changes to run with that version!**

**Review by dmulloy2 — APPROVED** [review]

**Comment by Rothes** [comment]
Bug, no messages are displayed on clients
```
[13:09:37] [Server thread/INFO]: Rothes issued server command: /psr capture add Chat
[13:09:37] [Netty Server IO #2/ERROR]: Error receiving packet 48
[13:11:56] [Server thread/INFO]: Rothes issued server command: /psr
[13:11:56] [Netty Server IO #0/ERROR]: Error receiving packet 48
[13:11:56] [Netty Server IO #0/ERROR]: Error receiving packet 48
[13:11:56] [Netty Server IO #0/ERROR]: Error receiving packet 48
[13:11:56] [Netty Server IO #0/ERROR]: Error receiving packet 48
[13:11:56] [Netty Server IO #0/ERROR]: Error receiving packet 48
[13:11:56] [Netty Server IO #0/ERROR]: Error receiving packet 48
```
Code:
```Java
            PacketContainer packet = new PacketContainer(PacketType.Play.Server.CHAT);
            packet.getChatComponents().write(0, ComponentConverter.fromBaseComponent(baseComponents));
            packet.getChatTypes().write(0, EnumWrappers.ChatType.SYSTEM);
            packet.setMeta("psr_filtered_packet", true);
            try {
                ProtocolStringReplacer.getInstance().getPacketListenerManager().getProtocolManager().
                        sendServerPacket(player, packet);
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }
```
*Also [GitHub here](https://github.com/Rothes/ProtocolStringReplacer/blob/cc039ca47f362bb0afac5014cc4a77de1deb713c/src/main/java/me/rothes/protocolstringreplacer/api/user/PsrUser.java#L224)*

**Comment by derklaro** [comment]
There is now a new SystemChat packet to send system chat messages, the normal chat packet requires you to have a signed version of the content:
image

You want to send the system chat message, with the type id set to 1:
image

(If you need any more packet field types, they are listed [here](https://protocol.derklaro.dev/))

**Comment by LOOHP** [comment]
I seemed to have found a different bug.
```java
protocolManager.addPacketListener(new PacketAdapter(PacketAdapter.params().optionAsync().plugin(plugin).types(PacketType.Status.Server.SERVER_INFO)) {
            @Override
            public void onPacketSending(PacketEvent event) {
                       ....
            }
}
```
It seems that SERVER_INFO listeners aren't getting called.

**Comment by Rothes** [comment]
> There is now a new SystemChat packet to send system chat messages, the normal chat packet requires you to have a signed version of the content: image
> 
> You want to send the system chat message, with the type id set to 1: image
> 
> (If you need any more packet field types, they are listed [here](https://protocol.derklaro.dev/))

Thanks for the info. Is there any Maven repo for the dev version..?

**Comment by derklaro** [comment]
I doesn't seem like the latest builds were deployed to the maven repo. However you can use jitpack instead: https://jitpack.io/#dmulloy2/ProtocolLib/master-SNAPSHOT

**Comment by derklaro** [comment]
> I seemed to have found a different bug.
> 
> ```java
> protocolManager.addPacketListener(new PacketAdapter(PacketAdapter.params().optionAsync().plugin(plugin).types(PacketType.Status.Server.SERVER_INFO)) {
>             @Override
>             public void onPacketSending(PacketEvent event) {
>                        ....
>             }
> }
> ```
> 
> It seems that SERVER_INFO listeners aren't getting called. It used to be called correctly back in 1.18.2.

Intersting... Please open an issue and I will take a look later :)

**Pull request merged**
